# Generated by Django 4.2.3 on 2024-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('category_of_usage', models.CharField(blank=True, null=True)),
                ('product_of_usage', models.CharField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
