# Generated by Django 4.2.3 on 2024-02-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('loyal_program', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='profile',
            field=models.ManyToManyField(related_name='promocodes', to='users.profile'),
        ),
    ]
