# Generated by Django 4.2.3 on 2023-12-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Мобильный телефон')),
                ('email_for_reset', models.EmailField(default='', max_length=254, null=True, unique=True, verbose_name='Адрес электронной почты')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('index', models.CharField(blank=True, max_length=200)),
                ('house', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('corp', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
                ('current_bonuses', models.IntegerField(default=0)),
                ('future_bonuses', models.IntegerField(default=0)),
                ('aroma_balls', models.IntegerField(default=0)),
                ('loyal_status', models.CharField(default='Новичок')),
                ('yandex_pay', models.BigIntegerField(default=0)),
                ('tinkoff_pay', models.BigIntegerField(default=0)),
                ('card_field', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=769294)),
                ('order_date', models.CharField()),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('created', 'Создан'), ('accepted', 'Принят'), ('completed', 'Доставлено')], default='processing', max_length=100)),
                ('shipping_address', models.CharField(null=True)),
                ('order_price', models.IntegerField(default=0)),
                ('name', models.CharField(null=True)),
                ('phone', models.CharField(null=True)),
                ('product', models.ManyToManyField(to='product.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
