# Generated by Django 4.2.3 on 2024-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_first_name_order_last_name_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=486550, unique=True),
        ),
    ]
