# Generated by Django 4.2.3 on 2023-09-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_order_number_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tinkoff_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='yandex_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=136008),
        ),
    ]
