# Generated by Django 4.2.3 on 2023-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_name_order_order_price_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=271681),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0),
        ),
    ]
