# Generated by Django 4.2.3 on 2024-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ml',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
