# Generated by Django 4.2.3 on 2024-02-20 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=539760, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('created', 'Создан'), ('accepted', 'Принят'), ('completed', 'Доставлено')], default='processing', max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('shipment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('index', models.CharField(blank=True, max_length=200, null=True)),
                ('house', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
                ('corp', models.CharField(blank=True, max_length=200, null=True)),
                ('shipment_date', models.CharField(blank=True, max_length=20, null=True)),
                ('order_price', models.FloatField(default=0.0)),
                ('loyal_status', models.CharField(default='Новичок')),
            ],
        ),
    ]
